-- ============================================================
--  Alzinger PV-Monitoring · Supabase / Postgres Schema
-- ============================================================
--  Dokumentation/Referenz des bereits in Supabase angelegten Schemas.
--  Idempotent ausführbar (create if not exists / create or replace).
--
--  Datenfluss:
--    Collector (service_role)  --INSERT/UPSERT-->  pv_live + pv_samples
--    App (anon/publishable)    --SELECT--------->  pv_live + Views
--
--  Zeitzone aller Tages-/Monats-/Kurven-Aggregate: Europe/Berlin.
-- ============================================================

-- ---------- Tabellen ----------

-- Aktueller Stand je Anlage (Upsert auf plant)
create table if not exists public.pv_live (
  plant      text primary key,            -- 'voll' | 'eigen'
  ts         timestamptz not null default now(),
  p_kw       double precision,            -- Erzeugung (Summe Wechselrichter)
  load_kw    double precision,            -- Verbrauch Werk (nur eigen)
  feed_kw    double precision,            -- Einspeisung ins Netz
  grid_kw    double precision,            -- Netzbezug aus dem Netz (nur eigen)
  total_kwh  double precision             -- Gesamtertrag (kumuliert, Zählerstand)
);

-- Zeitreihe – jeder Collector-Tick ein Sample je Anlage
create table if not exists public.pv_samples (
  id         bigint generated by default as identity primary key,
  ts         timestamptz not null default now(),
  plant      text not null,
  p_kw       double precision,
  load_kw    double precision,
  feed_kw    double precision,
  grid_kw    double precision,
  total_kwh  double precision
);

-- Index für die Zeitreihen-Abfragen der Views
create index if not exists pv_samples_plant_ts_idx on public.pv_samples (plant, ts);

-- Zähler-kWh-Stände (bezogene / eingespeiste Energie) – optional, nullable.
-- Werden vom Collector befüllt, wenn METER_IMPORT_REG/METER_EXPORT_REG gesetzt sind.
alter table public.pv_live    add column if not exists import_kwh double precision;
alter table public.pv_live    add column if not exists export_kwh double precision;
alter table public.pv_samples add column if not exists import_kwh double precision;
alter table public.pv_samples add column if not exists export_kwh double precision;

-- ---------- Views (alle in Europe/Berlin) ----------

-- 15-Minuten-Kurve für HEUTE. Spalte "slot" ist ein lokaler Zeitstempel
-- (Berlin); die App liest daraus per /T(\d\d):(\d\d)/ den Viertelstunden-Index.
create or replace view public.pv_today as
select
  plant,
  date_trunc('hour', ts at time zone 'Europe/Berlin')
    + (floor(extract(minute from ts at time zone 'Europe/Berlin') / 15) * interval '15 minutes') as slot,
  avg(p_kw)    as p_kw,
  avg(load_kw) as load_kw,
  avg(feed_kw) as feed_kw,
  avg(grid_kw) as grid_kw
from public.pv_samples
where (ts at time zone 'Europe/Berlin')::date = (now() at time zone 'Europe/Berlin')::date
group by plant, slot
order by slot;

-- Tagesenergie = max(total_kwh) - min(total_kwh) je Tag (kumulierter Zähler)
create or replace view public.pv_daily as
select
  plant,
  (ts at time zone 'Europe/Berlin')::date as tag,
  max(total_kwh) - min(total_kwh) as gen_kwh
from public.pv_samples
where total_kwh is not null
group by plant, tag
order by tag;

-- Monatsenergie analog, monat als Text 'YYYY-MM'
create or replace view public.pv_monthly as
select
  plant,
  to_char(ts at time zone 'Europe/Berlin', 'YYYY-MM') as monat,
  max(total_kwh) - min(total_kwh) as gen_kwh
from public.pv_samples
where total_kwh is not null
group by plant, monat
order by monat;

-- Zähler-Energie je Tag / Monat (Bezug/Einspeisung in kWh aus den Zählerständen)
create or replace view public.pv_meter_daily as
select
  plant,
  (ts at time zone 'Europe/Berlin')::date as tag,
  max(import_kwh) - min(import_kwh) as import_kwh,
  max(export_kwh) - min(export_kwh) as export_kwh
from public.pv_samples
where import_kwh is not null
group by plant, tag
order by tag;

create or replace view public.pv_meter_monthly as
select
  plant,
  to_char(ts at time zone 'Europe/Berlin', 'YYYY-MM') as monat,
  max(import_kwh) - min(import_kwh) as import_kwh,
  max(export_kwh) - min(export_kwh) as export_kwh
from public.pv_samples
where import_kwh is not null
group by plant, monat
order by monat;

-- ---------- Row Level Security ----------
-- anon/publishable darf NUR lesen; Schreiben ausschließlich mit service_role
-- (service_role umgeht RLS grundsätzlich).

alter table public.pv_live    enable row level security;
alter table public.pv_samples enable row level security;

drop policy if exists "anon read pv_live"    on public.pv_live;
drop policy if exists "anon read pv_samples" on public.pv_samples;

create policy "anon read pv_live"    on public.pv_live    for select to anon using (true);
create policy "anon read pv_samples" on public.pv_samples for select to anon using (true);

-- Leserechte auf Tabellen und Views für die öffentlichen Rollen
grant usage on schema public to anon, authenticated;
grant select on public.pv_live, public.pv_samples to anon, authenticated;
grant select on public.pv_today, public.pv_daily, public.pv_monthly to anon, authenticated;
grant select on public.pv_meter_daily, public.pv_meter_monthly to anon, authenticated;

-- ---------- Werksverbrauch (Energie aus der Verbrauchsleistung) ----------
-- Zeitgewichtete Integration von load_kw (Anlage 'eigen'); Lücken auf max. 5 Min
-- begrenzt, damit Ausfälle die Summe nicht aufblähen. Ergebnis in kWh.
create or replace view public.pv_load_daily as
with s as (
  select ts, load_kw, lead(ts) over (order by ts) as ts_next
  from public.pv_samples where plant = 'eigen' and load_kw is not null
)
select (ts at time zone 'Europe/Berlin')::date as tag,
       sum(greatest(load_kw,0) * extract(epoch from (least(ts_next, ts + interval '5 minutes') - ts)) / 3600.0) as load_kwh
from s where ts_next is not null
group by tag order by tag;

create or replace view public.pv_load_monthly as
with s as (
  select ts, load_kw, lead(ts) over (order by ts) as ts_next
  from public.pv_samples where plant = 'eigen' and load_kw is not null
)
select to_char(ts at time zone 'Europe/Berlin', 'YYYY-MM') as monat,
       sum(greatest(load_kw,0) * extract(epoch from (least(ts_next, ts + interval '5 minutes') - ts)) / 3600.0) as load_kwh
from s where ts_next is not null
group by monat order by monat;

grant select on public.pv_load_daily, public.pv_load_monthly to anon, authenticated;

-- ---------- Historischer Import (aus SmartLogger-/FusionSolar-Export) ----------
-- Erzeugung je Tag/Monat aus den Logger-Exporten; die App mischt sie mit den
-- Live-Daten (Live hat Vorrang bei gleichem Datum/Monat).
create table if not exists public.pv_hist_daily (
  plant text, tag date, gen_kwh double precision,
  primary key (plant, tag)
);
create table if not exists public.pv_hist_monthly (
  plant text, monat text, gen_kwh double precision,
  primary key (plant, monat)
);
alter table public.pv_hist_daily   enable row level security;
alter table public.pv_hist_monthly enable row level security;
drop policy if exists "anon read pv_hist_daily"   on public.pv_hist_daily;
drop policy if exists "anon read pv_hist_monthly" on public.pv_hist_monthly;
create policy "anon read pv_hist_daily"   on public.pv_hist_daily   for select to anon using (true);
create policy "anon read pv_hist_monthly" on public.pv_hist_monthly for select to anon using (true);
grant select on public.pv_hist_daily, public.pv_hist_monthly to anon, authenticated;

-- ---------- Börsen-Spotpreise ----------
-- Vom Collector server-seitig befüllt (Energy-Charts), damit der Browser sie
-- nicht selbst laden muss (kein CORS-Problem). Preis in ct/kWh je Viertelstunde.
create table if not exists public.pv_spot (
  slot  timestamptz primary key,
  price double precision
);
alter table public.pv_spot enable row level security;
drop policy if exists "anon read pv_spot" on public.pv_spot;
create policy "anon read pv_spot" on public.pv_spot for select to anon using (true);

-- Heutige Spotpreise (Europe/Berlin); slot als lokaler Zeitstempel für die App.
create or replace view public.pv_spot_today as
select (slot at time zone 'Europe/Berlin') as slot, price
from public.pv_spot
where (slot at time zone 'Europe/Berlin')::date = (now() at time zone 'Europe/Berlin')::date
order by slot;

-- Spotpreise heute + morgen (48 h) für die Vorschau-Kurve
create or replace view public.pv_spot_window as
select (slot at time zone 'Europe/Berlin') as slot, price
from public.pv_spot
where (slot at time zone 'Europe/Berlin') >= date_trunc('day', now() at time zone 'Europe/Berlin')
  and (slot at time zone 'Europe/Berlin') <  date_trunc('day', now() at time zone 'Europe/Berlin') + interval '2 days'
order by slot;

grant select on public.pv_spot to anon, authenticated;
grant select on public.pv_spot_today, public.pv_spot_window to anon, authenticated;

-- ---------- Abschaltungs-Erkennung (Erzeugung = 0 tagsüber) ----------
-- Erkennt je Anlage zusammenhängende Phasen, in denen tagsüber (10:00–17:00
-- Europe/Berlin) die Erzeugung auf 0 lag (p_kw <= 1 kW). Das ist das direkte
-- Signal für eine Abschaltung – im Kernzeitfenster sollte immer Leistung da sein.
-- "Gaps & Islands": fortlaufende Null-Phasen werden über die Differenz zweier
-- Zeilennummern zu Ereignissen gruppiert. Nur Phasen ab 10 Min Dauer zählen
-- (filtert kurze Messaussetzer/Wolken-Flacker heraus).
create or replace view public.pv_zero_events as
with f as (
  select plant,
         (ts at time zone 'Europe/Berlin')::date as tag,
         (ts at time zone 'Europe/Berlin')        as lts,
         (coalesce(p_kw,0) <= 1)                   as null_kw
  from public.pv_samples
  where p_kw is not null
    and extract(hour from (ts at time zone 'Europe/Berlin')) between 10 and 16  -- 10:00–16:59
),
m as (
  select *,
    row_number() over (partition by plant, tag order by lts)
    - row_number() over (partition by plant, tag, null_kw order by lts) as grp
  from f
)
select plant,
       tag,
       min(lts)                                                     as von,
       max(lts)                                                     as bis,
       round(extract(epoch from (max(lts) - min(lts))) / 60.0)::int as dauer_min
from m
where null_kw
group by plant, tag, grp
having (max(lts) - min(lts)) >= interval '10 minutes'
order by von;

grant select on public.pv_zero_events to anon, authenticated;
